version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      DB_CONNECTION: pgsql://user:${PASS}@localhost:5432/pgsql
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_USER: user
      POSTGRES_DB: pgsql
    volumes:
      - pgdata:/var/lib/postgresql/data
  sveltekit:
    build: .
    container_name: sveltekit
    restart: always
    ports:
      - '8001:3000'
    environment:
      CONNECTION_STRING: pgsql://user:${PASS}@db:5432/pgsql
volumes:
  pgdata:
    driver: local
